name: 'check update'
on:
  workflow_dispatch:
  schedule:
    # 每天8,12,16,20点检测一次
    - cron: '0 0,4,8,12 * * *'
permissions: {}
jobs:
  check-update:
    runs-on: ubuntu-latest
    name: Check Update
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: lts/Hydrogen
      - run: npm install semver cheerio js-yaml
      - uses: actions/github-script@v6
        env:
          SECRETS: ${{ toJSON(secrets) }}
        with:
          # script
          github-token: ${{ secrets.BOT_PAT }}
          script: |
            require('.github/scripts/run-task.js')({ github, context, core, glob, io, exec, fetch, require }, "packages/**/update.task.js");
